# Generated by Django 2.0.5 on 2019-08-25 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=1000)),
                ('passcode', models.CharField(max_length=1000)),
                ('time', models.IntegerField(max_length=1000)),
                ('amount', models.CharField(max_length=1000)),
                ('expired', models.CharField(max_length=1000)),
            ],
        ),
    ]
