# Generated by Django 2.0.5 on 2019-08-26 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_buffer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_User', models.CharField(max_length=1000)),
                ('to_User', models.CharField(max_length=1000)),
                ('time', models.CharField(max_length=1000)),
                ('amount', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='buffer',
            name='time',
            field=models.IntegerField(),
        ),
    ]
