# Generated by Django 2.0.5 on 2019-08-27 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_profile_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grp_name', models.CharField(max_length=1000)),
                ('grp_leader', models.CharField(max_length=1000)),
                ('friends', models.CharField(max_length=1000)),
            ],
        ),
    ]
